# Generated by Django 4.2.11 on 2024-05-04 22:55

import account.querysets.user_queryset
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.querysets.user_queryset.CustomUserManager()),
            ],
        ),
    ]
