services:
  redis:
    container_name: "platfo-redis"
    restart: unless-stopped
    image: bitnami/redis:6.2.12
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env

volumes:
  redis-data:
