# Generated by Django 4.2.11 on 2024-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=13, verbose_name='receiver number')),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_id', models.CharField(blank=True, max_length=30, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('plain_text', models.TextField(blank=True, null=True, verbose_name='sms content')),
            ],
        ),
    ]
